# render.yaml
services:
  - type: web
    name: war-board-gamerank
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: war-database
          property: connectionString

databases:
  - name: war-database
    databaseName: wardb
    user: wardb_user
